name: WARP VPN Downloader

on:
  workflow_dispatch:

jobs:
  test-download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Show Original GitHub IP
        run: curl -4 ifconfig.me

      - name: Install Cloudflare WARP VPN (Physical IP Override)
        run: |
          curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
          sudo apt-get update && sudo apt-get install -y cloudflare-warp
          # Setup and connect the VPN
          warp-cli --accept-tos registration new
          warp-cli --accept-tos connect
          sleep 10

      - name: Show New VPN IP Address
        run: curl -4 ifconfig.me

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Python Dependencies (Using Bleeding Edge yt-dlp)
        run: |
          pip install -r requirements.txt
          pip install -U --pre "yt-dlp[default]"

      - name: Run VPN Downloader Script
        run: python app.py

      - name: Upload Video Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-youtube-video
          path: test_video.mp4
          retention-days: 1
