name: Ultimate Repo Compilation Test

on:
  workflow_dispatch:

jobs:
  test-download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Override GitHub DNS
        run: |
          sudo bash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf'
          sudo bash -c 'echo "nameserver 1.1.1.1" >> /etc/resolv.conf'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install FFmpeg & Tor
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg tor
          sudo systemctl start tor

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Run The Master Script
        run: python app.py

      - name: Upload Video Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-youtube-video
          path: test_video.mp4
          retention-days: 1
